# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T12:40:08+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class ContainerARN(
    RootModel[
        constr(
            pattern=r'arn:aws:mediastore:[a-z]+-[a-z]+-\d:\d{12}:container/[\w-]{1,255}',
            min_length=1,
            max_length=1024,
        )
    ]
):
    root: constr(
        pattern=r'arn:aws:mediastore:[a-z]+-[a-z]+-\d:\d{12}:container/[\w-]{1,255}',
        min_length=1,
        max_length=1024,
    )


class ContainerAccessLoggingEnabled(RootModel[bool]):
    root: bool


class ContainerInUseException(RootModel[Any]):
    root: Any


class ContainerLevelMetrics(Enum):
    ENABLED = 'ENABLED'
    DISABLED = 'DISABLED'


class ContainerListLimit(RootModel[conint(ge=1, le=100)]):
    root: conint(ge=1, le=100)


class ContainerName(RootModel[constr(pattern=r'[\w-]+', min_length=1, max_length=255)]):
    root: constr(pattern=r'[\w-]+', min_length=1, max_length=255)


class ContainerNotFoundException(RootModel[Any]):
    root: Any


class ContainerPolicy(
    RootModel[constr(pattern=r'[\x00-\x7F]+', min_length=1, max_length=8192)]
):
    root: constr(pattern=r'[\x00-\x7F]+', min_length=1, max_length=8192)


class ContainerStatus(Enum):
    ACTIVE = 'ACTIVE'
    CREATING = 'CREATING'
    DELETING = 'DELETING'


class CorsPolicyNotFoundException(RootModel[Any]):
    root: Any


class DeleteContainerInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')


class DeleteContainerOutput(BaseModel):
    pass


class DeleteContainerPolicyInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')


class DeleteContainerPolicyOutput(BaseModel):
    pass


class DeleteCorsPolicyInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')


class DeleteCorsPolicyOutput(BaseModel):
    pass


class DeleteLifecyclePolicyInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')


class DeleteLifecyclePolicyOutput(BaseModel):
    pass


class DeleteMetricPolicyInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')


class DeleteMetricPolicyOutput(BaseModel):
    pass


class DescribeContainerInput(BaseModel):
    ContainerName_1: Optional[ContainerName] = Field(None, alias='ContainerName')


class Endpoint(
    RootModel[
        constr(
            pattern=r'[\u0009\u000A\u000D\u0020-\u00FF]+', min_length=1, max_length=255
        )
    ]
):
    root: constr(
        pattern=r'[\u0009\u000A\u000D\u0020-\u00FF]+', min_length=1, max_length=255
    )


class GetContainerPolicyInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')


class GetContainerPolicyOutput(BaseModel):
    Policy: ContainerPolicy


class GetCorsPolicyInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')


class GetLifecyclePolicyInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')


class GetMetricPolicyInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')


class Header(
    RootModel[
        constr(
            pattern=r'[\u0009\u000A\u000D\u0020-\u00FF]+', min_length=1, max_length=8192
        )
    ]
):
    root: constr(
        pattern=r'[\u0009\u000A\u000D\u0020-\u00FF]+', min_length=1, max_length=8192
    )


class InternalServerError(RootModel[Any]):
    root: Any


class LifecyclePolicy(
    RootModel[
        constr(
            pattern=r'[\u0009\u000A\u000D\u0020-\u00FF]+', min_length=0, max_length=8192
        )
    ]
):
    root: constr(
        pattern=r'[\u0009\u000A\u000D\u0020-\u00FF]+', min_length=0, max_length=8192
    )


class LimitExceededException(RootModel[Any]):
    root: Any


class ListTagsForResourceInput(BaseModel):
    Resource: ContainerARN


class MaxAgeSeconds(RootModel[conint(ge=0, le=2147483647)]):
    root: conint(ge=0, le=2147483647)


class MethodName(Enum):
    PUT = 'PUT'
    GET = 'GET'
    DELETE = 'DELETE'
    HEAD = 'HEAD'


class ObjectGroup(
    RootModel[
        constr(
            pattern=r'/?(?:[A-Za-z0-9_=:\.\-\~\*]+/){0,10}(?:[A-Za-z0-9_=:\.\-\~\*]+)?/?',
            min_length=1,
            max_length=900,
        )
    ]
):
    root: constr(
        pattern=r'/?(?:[A-Za-z0-9_=:\.\-\~\*]+/){0,10}(?:[A-Za-z0-9_=:\.\-\~\*]+)?/?',
        min_length=1,
        max_length=900,
    )


class ObjectGroupName(
    RootModel[constr(pattern=r'[a-zA-Z0-9_]+', min_length=1, max_length=30)]
):
    root: constr(pattern=r'[a-zA-Z0-9_]+', min_length=1, max_length=30)


class Origin(
    RootModel[
        constr(
            pattern=r'[\u0009\u000A\u000D\u0020-\u00FF]+', min_length=1, max_length=2048
        )
    ]
):
    root: constr(
        pattern=r'[\u0009\u000A\u000D\u0020-\u00FF]+', min_length=1, max_length=2048
    )


class PaginationToken(
    RootModel[constr(pattern=r'[0-9A-Za-z=/+]+', min_length=1, max_length=1024)]
):
    root: constr(pattern=r'[0-9A-Za-z=/+]+', min_length=1, max_length=1024)


class PolicyNotFoundException(RootModel[Any]):
    root: Any


class PutContainerPolicyInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')
    Policy: ContainerPolicy


class PutContainerPolicyOutput(BaseModel):
    pass


class PutCorsPolicyOutput(BaseModel):
    pass


class PutLifecyclePolicyInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')
    LifecyclePolicy_1: LifecyclePolicy = Field(..., alias='LifecyclePolicy')


class PutLifecyclePolicyOutput(BaseModel):
    pass


class PutMetricPolicyOutput(BaseModel):
    pass


class StartAccessLoggingInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')


class StartAccessLoggingOutput(BaseModel):
    pass


class StopAccessLoggingInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')


class StopAccessLoggingOutput(BaseModel):
    pass


class TagKey(
    RootModel[
        constr(pattern=r'[\p{L}\p{Z}\p{N}_.:/=+\-@]*', min_length=1, max_length=128)
    ]
):
    root: constr(pattern=r'[\p{L}\p{Z}\p{N}_.:/=+\-@]*', min_length=1, max_length=128)


class TagKeyList(RootModel[List[TagKey]]):
    root: List[TagKey]


class TagResourceOutput(BaseModel):
    pass


class TagValue(
    RootModel[
        constr(pattern=r'[\p{L}\p{Z}\p{N}_.:/=+\-@]*', min_length=0, max_length=256)
    ]
):
    root: constr(pattern=r'[\p{L}\p{Z}\p{N}_.:/=+\-@]*', min_length=0, max_length=256)


class TimeStamp(RootModel[datetime]):
    root: datetime


class UntagResourceInput(BaseModel):
    Resource: ContainerARN
    TagKeys: TagKeyList


class UntagResourceOutput(BaseModel):
    pass


class XAmzTarget(Enum):
    MediaStore_20170901_CreateContainer = 'MediaStore_20170901.CreateContainer'


class XAmzTarget1(Enum):
    MediaStore_20170901_DeleteContainer = 'MediaStore_20170901.DeleteContainer'


class XAmzTarget2(Enum):
    MediaStore_20170901_DeleteContainerPolicy = (
        'MediaStore_20170901.DeleteContainerPolicy'
    )


class XAmzTarget3(Enum):
    MediaStore_20170901_DeleteCorsPolicy = 'MediaStore_20170901.DeleteCorsPolicy'


class XAmzTarget4(Enum):
    MediaStore_20170901_DeleteLifecyclePolicy = (
        'MediaStore_20170901.DeleteLifecyclePolicy'
    )


class XAmzTarget5(Enum):
    MediaStore_20170901_DeleteMetricPolicy = 'MediaStore_20170901.DeleteMetricPolicy'


class XAmzTarget6(Enum):
    MediaStore_20170901_DescribeContainer = 'MediaStore_20170901.DescribeContainer'


class XAmzTarget7(Enum):
    MediaStore_20170901_GetContainerPolicy = 'MediaStore_20170901.GetContainerPolicy'


class XAmzTarget8(Enum):
    MediaStore_20170901_GetCorsPolicy = 'MediaStore_20170901.GetCorsPolicy'


class XAmzTarget9(Enum):
    MediaStore_20170901_GetLifecyclePolicy = 'MediaStore_20170901.GetLifecyclePolicy'


class XAmzTarget10(Enum):
    MediaStore_20170901_GetMetricPolicy = 'MediaStore_20170901.GetMetricPolicy'


class XAmzTarget11(Enum):
    MediaStore_20170901_ListContainers = 'MediaStore_20170901.ListContainers'


class XAmzTarget12(Enum):
    MediaStore_20170901_ListTagsForResource = 'MediaStore_20170901.ListTagsForResource'


class XAmzTarget13(Enum):
    MediaStore_20170901_PutContainerPolicy = 'MediaStore_20170901.PutContainerPolicy'


class XAmzTarget14(Enum):
    MediaStore_20170901_PutCorsPolicy = 'MediaStore_20170901.PutCorsPolicy'


class XAmzTarget15(Enum):
    MediaStore_20170901_PutLifecyclePolicy = 'MediaStore_20170901.PutLifecyclePolicy'


class XAmzTarget16(Enum):
    MediaStore_20170901_PutMetricPolicy = 'MediaStore_20170901.PutMetricPolicy'


class XAmzTarget17(Enum):
    MediaStore_20170901_StartAccessLogging = 'MediaStore_20170901.StartAccessLogging'


class XAmzTarget18(Enum):
    MediaStore_20170901_StopAccessLogging = 'MediaStore_20170901.StopAccessLogging'


class XAmzTarget19(Enum):
    MediaStore_20170901_TagResource = 'MediaStore_20170901.TagResource'


class XAmzTarget20(Enum):
    MediaStore_20170901_UntagResource = 'MediaStore_20170901.UntagResource'


class AllowedHeaders(RootModel[List[Header]]):
    root: List[Header] = Field(..., max_length=100, min_length=0)


class AllowedMethods(RootModel[List[MethodName]]):
    root: List[MethodName] = Field(..., max_length=4, min_length=1)


class AllowedOrigins(RootModel[List[Origin]]):
    root: List[Origin] = Field(..., max_length=100, min_length=1)


class Container(BaseModel):
    ARN: Optional[ContainerARN] = None
    AccessLoggingEnabled: Optional[ContainerAccessLoggingEnabled] = None
    CreationTime: Optional[TimeStamp] = None
    Endpoint_1: Optional[Endpoint] = Field(None, alias='Endpoint')
    Name: Optional[ContainerName] = None
    Status: Optional[ContainerStatus] = None


class ContainerList(RootModel[List[Container]]):
    root: List[Container]


class CreateContainerOutput(BaseModel):
    Container_1: Container = Field(..., alias='Container')


class DescribeContainerOutput(BaseModel):
    Container_1: Optional[Container] = Field(None, alias='Container')


class ExposeHeaders(RootModel[List[Header]]):
    root: List[Header] = Field(..., max_length=100, min_length=0)


class GetLifecyclePolicyOutput(BaseModel):
    LifecyclePolicy_1: LifecyclePolicy = Field(..., alias='LifecyclePolicy')


class ListContainersInput(BaseModel):
    MaxResults: Optional[ContainerListLimit] = None
    NextToken: Optional[PaginationToken] = None


class ListContainersOutput(BaseModel):
    Containers: ContainerList
    NextToken: Optional[PaginationToken] = None


class MetricPolicyRule(BaseModel):
    ObjectGroup_1: ObjectGroup = Field(..., alias='ObjectGroup')
    ObjectGroupName_1: ObjectGroupName = Field(..., alias='ObjectGroupName')


class MetricPolicyRules(RootModel[List[MetricPolicyRule]]):
    root: List[MetricPolicyRule] = Field(..., max_length=300, min_length=1)


class Tag(BaseModel):
    Key: TagKey
    Value: Optional[TagValue] = None


class TagList(RootModel[List[Tag]]):
    root: List[Tag] = Field(..., max_length=200, min_length=1)


class TagResourceInput(BaseModel):
    Resource: ContainerARN
    Tags: TagList


class CorsRule(BaseModel):
    AllowedHeaders_1: AllowedHeaders = Field(..., alias='AllowedHeaders')
    AllowedMethods_1: Optional[AllowedMethods] = Field(None, alias='AllowedMethods')
    AllowedOrigins_1: AllowedOrigins = Field(..., alias='AllowedOrigins')
    ExposeHeaders_1: Optional[ExposeHeaders] = Field(None, alias='ExposeHeaders')
    MaxAgeSeconds_1: Optional[MaxAgeSeconds] = Field(None, alias='MaxAgeSeconds')


class CreateContainerInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')
    Tags: Optional[TagList] = None


class ListTagsForResourceOutput(BaseModel):
    Tags: Optional[TagList] = None


class MetricPolicy(BaseModel):
    ContainerLevelMetrics_1: ContainerLevelMetrics = Field(
        ..., alias='ContainerLevelMetrics'
    )
    MetricPolicyRules_1: Optional[MetricPolicyRules] = Field(
        None, alias='MetricPolicyRules'
    )


class PutMetricPolicyInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')
    MetricPolicy_1: MetricPolicy = Field(..., alias='MetricPolicy')


class CorsPolicy(RootModel[List[CorsRule]]):
    root: List[CorsRule] = Field(
        ...,
        description='The CORS policy of the container. ',
        max_length=100,
        min_length=1,
    )


class GetCorsPolicyOutput(BaseModel):
    CorsPolicy_1: CorsPolicy = Field(..., alias='CorsPolicy')


class GetMetricPolicyOutput(BaseModel):
    MetricPolicy_1: MetricPolicy = Field(..., alias='MetricPolicy')


class PutCorsPolicyInput(BaseModel):
    ContainerName_1: ContainerName = Field(..., alias='ContainerName')
    CorsPolicy_1: CorsPolicy = Field(..., alias='CorsPolicy')
